### ISSUE TITLE
why does ROICtrl have better spatial alignment than ROICtrl (mask)?

### ISSUE THREAD

**Issue by 0xLDF** [showlab/ROICtrl#1]
Thank you for your excellent work. I am curious about one point in the paper: why does ROICtrl have better spatial alignment than ROICtrl (mask)? Logically, ROICtrl has undergone downsampling, which should result in the loss of information.

**Comment by guyuchao** [comment]
There are two reasons for this problem:

1) In the attention-mask version, we should quantize the box coordinates on a lower-resolution feature map. For example, in a 64x downsampled feature map (8x8), half-pixel (0.5) quantization can lead to a significant shift (about 32 pixels) in the decoded image. Additionally, if the object is smaller than 32x32, it may result in almost no activation in the smallest feature map when using the attention-mask.

2) The large-sized ROI undergoes downsampling, while the small-sized ROI undergoes upsampling, based on its actual size and the pre-defined ROI size. This approach ensures a uniform size for learning ROI text injection. Information change from roi-size change can be learned effectively. However, when using the ROICtrl structure in the attention-mask version, the model must handle dynamic feature sizes within the attention mask, which is more challenging to learn in practice.
